#!/usr/bin/env bash
set -euo pipefail

# EN: API probe script to capture request/response samples into a Markdown report.
# KO: 요청/응답 샘플을 Markdown 리포트로 저장하는 API 점검 스크립트.
#
# Usage:
#   ACCESS_TOKEN=... PROJECT_ID=... PLACE_ID=... LIVE_EVENT_ID=... \
#   bash scripts/api_probe.sh
#
# Optional:
#   BASE_URL=https://api.noraneko.cc
#   OUT=docs/api_probe_results.md
#   ALLOW_MUTATIONS=1   # Enable POST/DELETE verification (side effects)

BASE_URL="${BASE_URL:-http://localhost:8080}"
OUT="${OUT:-docs/api_probe_results.md}"
ALLOW_MUTATIONS="${ALLOW_MUTATIONS:-0}"

#
# EN: Inject credentials through the environment or the interactive prompt.
# KO: 자격 증명은 환경 변수 또는 대화형 프롬프트로 주입합니다.
ACCESS_TOKEN="${ACCESS_TOKEN:-}"
LOGIN_ENDPOINT="${LOGIN_ENDPOINT:-/api/v1/auth/login}"
LOGIN_EMAIL_KEY="${LOGIN_EMAIL_KEY:-username}"
LOGIN_PASSWORD_KEY="${LOGIN_PASSWORD_KEY:-password}"

LOGIN_EMAIL="${LOGIN_EMAIL:-}"
LOGIN_PASSWORD="${LOGIN_PASSWORD:-}"
PROJECT_ID="${PROJECT_ID:-}"
PLACE_ID="${PLACE_ID:-}"
LIVE_EVENT_ID="${LIVE_EVENT_ID:-}"
NEWS_ID="${NEWS_ID:-}"
POST_ID="${POST_ID:-}"

NOW="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"

if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required." >&2
  exit 1
fi

HAS_JQ=0
if command -v jq >/dev/null 2>&1; then
  HAS_JQ=1
fi

maybe_login() {
  if [[ -n "$ACCESS_TOKEN" ]]; then
    return
  fi

  if [[ $HAS_JQ -eq 0 ]]; then
    echo "jq is required for auto-login. Install jq or set ACCESS_TOKEN." >&2
    return
  fi

  if [[ -z "$LOGIN_EMAIL" ]]; then
    read -rp "Username: " LOGIN_EMAIL
  fi
  if [[ -z "$LOGIN_PASSWORD" ]]; then
    read -srp "Password: " LOGIN_PASSWORD
    echo
  fi

  if [[ -z "$LOGIN_EMAIL" || -z "$LOGIN_PASSWORD" ]]; then
    echo "Login skipped: missing email/password." >&2
    return
  fi

  local payload
  payload=$(jq -n \
    --arg email "$LOGIN_EMAIL" \
    --arg pass "$LOGIN_PASSWORD" \
    --arg ek "$LOGIN_EMAIL_KEY" \
    --arg pk "$LOGIN_PASSWORD_KEY" \
    '{($ek): $email, ($pk): $pass}')

  local response
  response=$(curl -sS -X POST "$BASE_URL$LOGIN_ENDPOINT" \
    -H "Content-Type: application/json" \
    -d "$payload")

  local token
  token=$(echo "$response" | jq -r '
    .data.accessToken //
    .data.access_token //
    .data.token //
    .accessToken //
    .access_token //
    .token //
    .data.tokens.accessToken //
    .tokens.accessToken //
    empty
  ')

  if [[ -z "$token" || "$token" == "null" ]]; then
    echo "Failed to extract access token from login response." >&2
    return
  fi

  ACCESS_TOKEN="$token"
}

write_header() {
  cat <<MD > "$OUT"
# API Probe Results

- GeneratedAt (UTC): $NOW
- BaseURL: $BASE_URL
- AllowMutations: $ALLOW_MUTATIONS

> EN: This file is auto-generated by scripts/api_probe.sh
> KO: 이 파일은 scripts/api_probe.sh로 자동 생성됩니다.

---
MD
}

write_section() {
  local title="$1"
  local url="$2"
  local auth="$3"
  local method="${4:-GET}"
  local data="${5:-}"

  {
    echo "## $title"
    echo
    echo "- Method: $method"
    echo "- URL: $url"
    echo "- Auth: $auth"
    echo
    echo "### Response"
    echo
  } >> "$OUT"

  local cmd=(curl -sS "$url")
  if [[ "$method" != "GET" ]]; then
    cmd=(curl -sS -X "$method" "$url" -H "Content-Type: application/json")
    if [[ -n "$data" ]]; then
      cmd+=( -d "$data" )
    fi
  fi
  if [[ "$auth" == "required" ]]; then
    if [[ -z "$ACCESS_TOKEN" ]]; then
      {
        echo "_Skipped: ACCESS_TOKEN missing_"
        echo
        echo "---"
      } >> "$OUT"
      return
    fi
    cmd+=( -H "Authorization: Bearer $ACCESS_TOKEN" )
  fi

  if [[ $HAS_JQ -eq 1 ]]; then
    "${cmd[@]}" | jq -S . >> "$OUT" 2>/dev/null || "${cmd[@]}" >> "$OUT"
  else
    "${cmd[@]}" >> "$OUT"
  fi

  {
    echo
    echo "---"
  } >> "$OUT"
}

write_header

maybe_login

# Search
write_section "Search (query + q)" \
  "$BASE_URL/api/v1/search?query=tokyo&q=tokyo" "public"

# Projects / Units
write_section "Projects" "$BASE_URL/api/v1/projects" "public"
if [[ -n "$PROJECT_ID" ]]; then
  write_section "Project Units" \
    "$BASE_URL/api/v1/projects/$PROJECT_ID/units" "public"
else
  {
    echo "## Project Units"
    echo
    echo "_Skipped: PROJECT_ID missing_"
    echo
    echo "---"
  } >> "$OUT"
fi

# Notifications
write_section "Notifications" "$BASE_URL/api/v1/notifications" "required"

# Favorites
write_section "Favorites" "$BASE_URL/api/v1/users/me/favorites" "required"
if [[ "$ALLOW_MUTATIONS" == "1" ]]; then
  write_section "Favorites Add" "$BASE_URL/api/v1/users/me/favorites" "required" \
    "POST" '{"targetId":"sample-id","targetType":"PLACE"}'
  write_section "Favorites Delete" "$BASE_URL/api/v1/users/me/favorites" "required" \
    "DELETE" '{"targetId":"sample-id","targetType":"PLACE"}'
fi

# Verification
write_section "Verification Challenge" \
  "$BASE_URL/api/v1/verification/challenge" "public"
if [[ "$ALLOW_MUTATIONS" == "1" && -n "$PROJECT_ID" && -n "$PLACE_ID" ]]; then
  write_section "Place Verification" \
    "$BASE_URL/api/v1/projects/$PROJECT_ID/places/$PLACE_ID/verification" \
    "required" "POST" '{"challengeToken":"sample-token"}'
else
  {
    echo "## Place Verification"
    echo
    echo "_Skipped: ALLOW_MUTATIONS=1 and PROJECT_ID/PLACE_ID required_"
    echo
    echo "---"
  } >> "$OUT"
fi
if [[ "$ALLOW_MUTATIONS" == "1" && -n "$PROJECT_ID" && -n "$LIVE_EVENT_ID" ]]; then
  write_section "Live Event Verification" \
    "$BASE_URL/api/v1/projects/$PROJECT_ID/live-events/$LIVE_EVENT_ID/verification" \
    "required" "POST" '{"challengeToken":"sample-token"}'
else
  {
    echo "## Live Event Verification"
    echo
    echo "_Skipped: ALLOW_MUTATIONS=1 and PROJECT_ID/LIVE_EVENT_ID required_"
    echo
    echo "---"
  } >> "$OUT"
fi

# Uploads
if [[ -n "$ACCESS_TOKEN" ]]; then
  write_section "My Uploads" "$BASE_URL/api/v1/uploads/my" "required"
else
  {
    echo "## My Uploads"
    echo
    echo "_Skipped: ACCESS_TOKEN missing_"
    echo
    echo "---"
  } >> "$OUT"
fi
if [[ "$ALLOW_MUTATIONS" == "1" ]]; then
  write_section "Presigned URL" \
    "$BASE_URL/api/v1/uploads/presigned-url" "required" \
    "POST" '{"fileName":"photo.jpg","contentType":"image/jpeg"}'
  if [[ -n "$PROJECT_ID" ]]; then
    write_section "Confirm Upload" \
      "$BASE_URL/api/v1/uploads/sample-upload-id/confirm" "required" \
      "POST" ''
    write_section "Delete Upload" \
      "$BASE_URL/api/v1/uploads/sample-upload-id" "required" \
      "DELETE" ''
  fi
fi

echo "Done. Output: $OUT"
