/// EN: Request DTO for X (Twitter) PKCE login (POST /api/v1/auth/oauth2/twitter).
/// KO: X (Twitter) PKCE 로그인 요청 DTO (POST /api/v1/auth/oauth2/twitter).
library;

/// EN: Carries the PKCE authorization code and verifier obtained from the
///     X OAuth 2.0 callback. The server uses these to exchange the code
///     for X access tokens, then issues its own JWT pair.
/// KO: X OAuth 2.0 콜백에서 수신한 PKCE 인가 코드와 verifier를 전달합니다.
///     서버는 이를 이용해 X 액세스 토큰을 교환하고 자체 JWT 쌍을 발급합니다.
class TwitterOAuthRequest {
  const TwitterOAuthRequest({
    required this.code,
    required this.codeVerifier,
    required this.redirectUri,
  });

  /// EN: Authorization code received in the redirect callback from X.
  /// KO: X 리다이렉트 콜백에서 수신한 인가 코드.
  final String code;

  /// EN: Original PKCE code_verifier generated by the app before launching the browser.
  /// KO: 브라우저 실행 전 앱이 생성한 원본 PKCE code_verifier.
  final String codeVerifier;

  /// EN: Redirect URI used in the authorization request — must exactly match.
  /// KO: 인가 요청 시 사용한 redirect URI — 정확히 동일해야 합니다.
  final String redirectUri;

  Map<String, dynamic> toJson() => {
    'code': code,
    'codeVerifier': codeVerifier,
    'redirectUri': redirectUri,
  };
}
