/// EN: Mobile-server endpoint contract catalog.
///     The baseline was imported from /v3/api-docs; changes made while the
///     server is stabilizing are reconciled manually and covered by focused
///     client contract tests until the next full OpenAPI refresh.
/// KO: 모바일-서버 엔드포인트 계약 카탈로그입니다.
///     기준은 /v3/api-docs에서 가져왔으며, 서버 안정화 중의 변경은
///     다음 전체 OpenAPI 갱신 전까지 수동 반영하고 클라이언트 계약 테스트로
///     보호합니다.
library;

class ApiV3EndpointCatalog {
  ApiV3EndpointCatalog._();

  /// EN: OpenAPI info version from the last imported server baseline.
  /// KO: 마지막으로 가져온 서버 기준선의 OpenAPI info 버전입니다.
  static const String specVersion = 'v1';

  /// EN: Path -> allowed HTTP methods map.
  /// KO: 경로 -> 허용 HTTP 메서드 맵입니다.
  static const Map<String, List<String>> pathMethods = {
    '/actuator': ['GET'],
    '/actuator/health': ['GET'],
    '/actuator/health/**': ['GET'],
    '/actuator/info': ['GET'],
    '/actuator/metrics': ['GET'],
    '/actuator/metrics/{requiredMetricName}': ['GET'],
    '/actuator/prometheus': ['GET'],
    '/api/v1/admin/analytics/visits/by-place': ['GET'],
    '/api/v1/admin/analytics/visits/timeseries': ['GET'],
    '/api/v1/admin/audit-logs': ['GET'],
    '/api/v1/admin/circuit-breakers': ['GET'],
    '/api/v1/admin/circuit-breakers/database': ['GET'],
    '/api/v1/admin/circuit-breakers/redis': ['GET'],
    '/api/v1/admin/community/reports': ['GET'],
    '/api/v1/admin/community/reports/{reportId}': ['GET', 'PATCH'],
    '/api/v1/admin/community/reports/{reportId}/assign': ['PATCH'],
    '/api/v1/admin/dashboard': ['GET'],
    '/api/v1/admin/events/stream': ['GET'],
    '/api/v1/admin/exports': ['POST'],
    '/api/v1/admin/exports/{id}': ['GET'],
    '/api/v1/admin/exports/{id}/download': ['GET'],
    '/api/v1/admin/insights/projects': ['GET'],
    '/api/v1/admin/insights/projects/{projectId}/units': ['GET'],
    '/api/v1/admin/media-deletions': ['GET'],
    '/api/v1/admin/media-deletions/{requestId}/approve': ['POST'],
    '/api/v1/admin/media-deletions/{requestId}/reject': ['POST'],
    '/api/v1/admin/moderation/dashboard': ['GET'],
    '/api/v1/admin/password-security/config': ['GET'],
    '/api/v1/admin/password-security/test': ['GET'],
    '/api/v1/admin/projects/role-requests': ['GET'],
    '/api/v1/admin/projects/role-requests/{requestId}': ['GET'],
    '/api/v1/admin/projects/role-requests/{requestId}/review': ['PATCH'],
    '/api/v1/admin/projects/{projectId}/verification-appeals': ['GET'],
    '/api/v1/admin/projects/{projectId}/verification-appeals/{appealId}': [
      'GET',
      'PATCH',
    ],
    '/api/v1/admin/stream/activity': ['GET'],
    '/api/v1/admin/tokens/revoke': ['POST'],
    '/api/v1/admin/users': ['GET'],
    '/api/v1/admin/users/blocks': ['GET'],
    '/api/v1/admin/users/{userId}': ['GET'],
    '/api/v1/admin/users/{userId}/active': ['POST'],
    '/api/v1/admin/users/{userId}/access-grants': ['POST'],
    '/api/v1/admin/users/{userId}/access-grants/{grantId}/revoke': ['POST'],
    '/api/v1/admin/users/{userId}/access-level': ['GET'],
    '/api/v1/admin/users/{userId}/blocks': ['DELETE', 'POST'],
    '/api/v1/admin/users/notifications/broadcast': ['POST'],
    '/api/v1/admin/users/notifications/test-send': ['POST'],
    '/api/v1/admin/users/{userId}/role': ['POST'],
    '/api/v1/admin/users/{userId}/sanctions': ['GET', 'POST'],
    '/api/v1/admin/users/{userId}/sanctions/{sanctionId}': ['DELETE'],
    '/api/v1/auth/email-verifications': ['POST'],
    '/api/v1/auth/email-verifications/confirm': ['POST'],
    '/api/v1/auth/account-recovery/apple': ['POST'],
    '/api/v1/auth/account-recovery/google': ['POST'],
    '/api/v1/auth/account-recovery/password': ['POST'],
    '/api/v1/auth/login': ['POST'],
    '/api/v1/auth/logout': ['POST'],
    '/api/v1/auth/oauth2/callback/{provider}': ['GET'],
    '/api/v1/auth/oauth2/connect/existing/apple': ['POST'],
    '/api/v1/auth/oauth2/connect/existing/google': ['POST'],
    '/api/v1/auth/refresh': ['POST'],
    '/api/v1/auth/register': ['POST'],
    '/api/v1/community/feed/recommended': ['GET'],
    '/api/v1/community/feed/recommended/cursor': ['GET'],
    '/api/v1/community/feed/following/cursor': ['GET'],
    '/api/v1/community/translations': ['POST'],
    '/api/v1/community/reports': ['POST'],
    '/api/v1/community/reports/me': ['GET'],
    '/api/v1/community/reports/{reportId}': ['DELETE', 'GET'],
    '/api/v1/community/subscriptions': ['GET'],
    '/api/v1/cheer-guides/{guideId}': ['GET'],
    '/api/v1/health': ['GET'],
    '/api/v1/health/detailed': ['GET'],
    '/api/v1/health/live': ['GET'],
    '/api/v1/health/ready': ['GET'],
    '/api/v1/home/summary': ['GET'],
    '/api/v1/home/summary/by-project': ['GET'],
    '/api/v1/notifications': ['GET'],
    '/api/v1/notifications/settings': ['GET', 'PUT'],
    '/api/v1/notifications/{id}/read': ['POST'],
    '/api/v1/places/{placeId}/comments': ['GET', 'POST'],
    '/api/v1/places/{placeId}/comments/batch': ['POST'],
    '/api/v1/places/{placeId}/comments/filter/accessibility': ['GET'],
    '/api/v1/places/{placeId}/comments/filter/advice': ['GET'],
    '/api/v1/places/{placeId}/comments/filter/photos': ['GET'],
    '/api/v1/places/{placeId}/comments/filter/routes': ['GET'],
    '/api/v1/places/{placeId}/comments/pinned': ['GET'],
    '/api/v1/places/{placeId}/comments/search': ['POST'],
    '/api/v1/places/{placeId}/comments/stats': ['GET'],
    '/api/v1/places/{placeId}/comments/tags/popular': ['GET'],
    '/api/v1/places/{placeId}/comments/threads/{threadId}': ['GET'],
    '/api/v1/places/{placeId}/comments/{commentId}': ['DELETE', 'PUT'],
    '/api/v1/places/{placeId}/comments/{commentId}/moderate': ['PUT'],
    '/api/v1/places/{placeId}/comments/{commentId}/reply': ['POST'],
    '/api/v1/places/{placeId}/guides': ['GET', 'POST'],
    '/api/v1/places/{placeId}/guides/all': ['GET'],
    '/api/v1/places/{placeId}/guides/batch': ['POST'],
    '/api/v1/places/{placeId}/guides/high-priority': ['GET'],
    '/api/v1/places/{placeId}/guides/search': ['POST'],
    '/api/v1/places/{placeId}/guides/unpublished': ['GET'],
    '/api/v1/places/{placeId}/guides/{guideId}': ['DELETE', 'GET', 'PUT'],
    '/api/v1/places/{placeId}/guides/{guideId}/preview': ['GET'],
    '/api/v1/places/{placeId}/guides/{guideId}/publish': ['PUT'],
    '/api/v1/places/{placeId}/photos': ['GET', 'POST'],
    '/api/v1/places/{placeId}/photos/all': ['GET'],
    '/api/v1/places/{placeId}/photos/batch': ['POST'],
    '/api/v1/places/{placeId}/photos/featured': ['GET'],
    '/api/v1/places/{placeId}/photos/pending': ['GET'],
    '/api/v1/places/{placeId}/photos/{photoId}': ['DELETE', 'GET', 'PUT'],
    '/api/v1/places/{placeId}/photos/{photoId}/approve': ['PUT'],
    '/api/v1/projects': ['GET', 'POST'],
    '/api/v1/projects/{projectCode}/comments/by-author/{userId}': ['GET'],
    '/api/v1/projects/{projectCode}/moderation/bans': ['GET'],
    '/api/v1/projects/{projectCode}/moderation/bans/{userId}': [
      'DELETE',
      'GET',
      'POST',
    ],
    '/api/v1/projects/{projectCode}/moderation/posts/{postId}': ['DELETE'],
    '/api/v1/projects/{projectCode}/moderation/posts/{postId}/comments/{commentId}':
        ['DELETE'],
    '/api/v1/projects/{projectCode}/posts': ['GET', 'POST'],
    '/api/v1/projects/{projectCode}/posts/by-author/{userId}': ['GET'],
    '/api/v1/projects/{projectCode}/posts/cursor': ['GET'],
    '/api/v1/projects/{projectCode}/posts/search': ['GET'],
    '/api/v1/projects/{projectCode}/posts/trending': ['GET'],
    '/api/v1/projects/{projectCode}/posts/{postId}': ['DELETE', 'GET', 'PUT'],
    '/api/v1/projects/{projectCode}/posts/{postId}/bookmark': [
      'DELETE',
      'GET',
      'POST',
    ],
    '/api/v1/projects/{projectCode}/posts/{postId}/comments': ['GET', 'POST'],
    '/api/v1/projects/{projectCode}/posts/{postId}/comments/thread': ['GET'],
    '/api/v1/projects/{projectCode}/posts/{postId}/comments/{commentId}': [
      'DELETE',
      'PUT',
    ],
    '/api/v1/projects/{projectCode}/posts/{postId}/like': [
      'DELETE',
      'GET',
      'POST',
    ],
    '/api/v1/projects/{projectCode}/travel-reviews': ['GET', 'POST'],
    '/api/v1/projects/{projectCode}/travel-reviews/{reviewId}': [
      'DELETE',
      'GET',
      'PATCH',
    ],
    '/api/v1/projects/{projectId}': ['DELETE', 'GET', 'PUT'],
    '/api/v1/projects/{projectId}/admin/live-events': ['GET'],
    '/api/v1/projects/{projectId}/admin/live-events/{liveEventId}/units:replace':
        ['POST'],
    '/api/v1/projects/{projectId}/admin/news/{newsId}/units:replace': ['POST'],
    '/api/v1/projects/{projectId}/admin/places/{placeId}/units:replace': [
      'POST',
    ],
    '/api/v1/projects/{projectId}/admin/places/{placeId}/visits': ['GET'],
    '/api/v1/projects/{projectId}/admin/places/{placeId}/visits/anomalies': [
      'GET',
    ],
    '/api/v1/projects/{projectId}/admin/places/{placeId}/visits/summary': [
      'GET',
    ],
    '/api/v1/projects/{projectId}/admin/places/{placeId}/visits/{visitId}/moderate':
        ['POST'],
    '/api/v1/projects/{projectId}/live-events': ['GET', 'POST'],
    '/api/v1/projects/{projectId}/live-events/{liveEventId}': [
      'DELETE',
      'GET',
      'PUT',
    ],
    '/api/v1/projects/{projectId}/live-events/{liveEventId}/banner': [
      'DELETE',
      'POST',
    ],
    '/api/v1/projects/{projectId}/live-events/attendances': ['GET'],
    '/api/v1/projects/{projectId}/live-events/{liveEventId}/attendance': [
      'GET',
      'PUT',
    ],
    '/api/v1/projects/{projectId}/live-events/{liveEventId}/setlist': ['GET'],
    '/api/v1/projects/{projectId}/live-events/{liveEventId}/verification': [
      'POST',
    ],
    '/api/v1/projects/{projectId}/music/albums': ['GET'],
    '/api/v1/projects/{projectId}/music/albums/{albumId}': ['GET'],
    '/api/v1/projects/{projectId}/music/songs': ['GET'],
    '/api/v1/projects/{projectId}/music/songs/{songId}': ['GET'],
    '/api/v1/projects/{projectId}/music/songs/{songId}/lyrics': ['GET'],
    '/api/v1/projects/{projectId}/music/songs/{songId}/parts': ['GET'],
    '/api/v1/projects/{projectId}/music/songs/{songId}/call-guide': ['GET'],
    '/api/v1/projects/{projectId}/music/songs/{songId}/versions': ['GET'],
    '/api/v1/projects/{projectId}/music/songs/{songId}/versions/{versionCode}':
        ['GET'],
    '/api/v1/projects/{projectId}/music/songs/{songId}/credits': ['GET'],
    '/api/v1/projects/{projectId}/music/songs/{songId}/difficulty': ['GET'],
    '/api/v1/projects/{projectId}/music/songs/{songId}/media-links': ['GET'],
    '/api/v1/projects/{projectId}/music/songs/{songId}/availability': ['GET'],
    '/api/v1/projects/{projectId}/music/songs/{songId}/live-context': ['GET'],
    '/api/v1/projects/{projectId}/news': ['GET', 'POST'],
    '/api/v1/projects/{projectId}/news/{newsId}': ['DELETE', 'GET', 'PUT'],
    '/api/v1/projects/{projectId}/news/{newsId}/images': ['POST'],
    '/api/v1/projects/{projectId}/news/{newsId}/images/{imageId}': ['DELETE'],
    '/api/v1/projects/{projectId}/news/{newsId}/images/{imageId}:primary': [
      'POST',
    ],
    '/api/v1/projects/{projectId}/news/{newsId}/images:reorder': ['POST'],
    '/api/v1/projects/{projectId}/place-types': ['GET', 'POST'],
    '/api/v1/projects/{projectId}/place-types/order': ['PUT'],
    '/api/v1/projects/{projectId}/places': ['GET', 'POST'],
    '/api/v1/projects/{projectId}/places/nearby': ['GET'],
    '/api/v1/projects/{projectId}/places/regions/available': ['GET'],
    '/api/v1/projects/{projectId}/places/regions/breadcrumb/{regionCode}': [
      'GET',
    ],
    '/api/v1/projects/{projectId}/places/regions/favorites': ['GET', 'POST'],
    '/api/v1/projects/{projectId}/places/regions/filter': ['GET'],
    '/api/v1/projects/{projectId}/places/regions/map-bounds': ['GET'],
    '/api/v1/projects/{projectId}/places/regions/stats': ['GET'],
    '/api/v1/projects/{projectId}/places/search/autocomplete': ['GET'],
    '/api/v1/projects/{projectId}/places/search/filters/available': ['GET'],
    '/api/v1/projects/{projectId}/places/search/popular': ['GET'],
    '/api/v1/projects/{projectId}/places/search/quick-filters': ['GET', 'POST'],
    '/api/v1/projects/{projectId}/places/search/regions/stats': ['GET'],
    '/api/v1/projects/{projectId}/places/search/suggestions': ['GET'],
    '/api/v1/projects/{projectId}/places/search/unified': ['GET'],
    '/api/v1/projects/{projectId}/places/within-bounds': ['GET'],
    '/api/v1/projects/{projectId}/places/{placeId}': ['DELETE', 'GET', 'PUT'],
    '/api/v1/projects/{projectId}/places/{placeId}/stats': ['GET'],
    '/api/v1/projects/{projectId}/places/{placeId}/images': ['POST'],
    '/api/v1/projects/{projectId}/places/{placeId}/images/{imageId}': [
      'DELETE',
    ],
    '/api/v1/projects/{projectId}/places/{placeId}/images/{imageId}:primary': [
      'POST',
    ],
    '/api/v1/projects/{projectId}/places/{placeId}/images:reorder': ['POST'],
    '/api/v1/projects/{projectId}/places/{placeId}/verification': ['POST'],
    '/api/v1/projects/{projectId}/rankings/most-liked': ['GET'],
    '/api/v1/projects/{projectId}/rankings/most-visited': ['GET'],
    '/api/v1/projects/{projectId}/rankings/trending': ['GET'],
    '/api/v1/projects/{projectId}/rankings/users': ['GET'],
    '/api/v1/projects/{projectId}/rankings/users/me': ['GET'],
    '/api/v1/quotes/{quoteId}/like': ['DELETE', 'POST'],
    '/api/v1/fan-subjects': ['GET'],
    '/api/v1/fan-subjects/{subjectId}': ['GET'],
    '/api/v1/fan-subjects/{subjectId}/children': ['GET'],
    '/api/v1/users/me/fan-subjects': ['GET'],
    '/api/v1/users/me/fan-subjects/{subjectId}': ['PUT', 'DELETE'],
    '/api/v1/users/me/fan-level': ['GET'],
    '/api/v1/users/me/fan-level/check-in': ['POST'],
    '/api/v1/projects/{projectId}/roles': ['GET'],
    '/api/v1/projects/{projectId}/roles/grant': ['POST'],
    '/api/v1/projects/{projectId}/roles/revoke': ['POST'],
    '/api/v1/projects/role-requests': ['GET', 'POST'],
    '/api/v1/projects/role-requests/{requestId}': ['DELETE', 'GET'],
    '/api/v1/projects/{projectId}/units': ['GET', 'POST'],
    '/api/v1/projects/{projectId}/units/search': ['GET'],
    '/api/v1/projects/{projectId}/units/{unitId}/members': ['GET', 'POST'],
    '/api/v1/projects/{projectId}/units/{unitId}/members/{memberId}': [
      'DELETE',
      'GET',
      'PUT',
    ],
    '/api/v1/projects/{projectId}/units/voice-actors': ['GET'],
    '/api/v1/projects/{projectId}/units/voice-actors/{voiceActorId}': ['GET'],
    '/api/v1/projects/{projectId}/units/voice-actors/{voiceActorId}/credits': [
      'GET',
    ],
    '/api/v1/projects/{projectId}/units/voice-actors/{voiceActorId}/members': [
      'GET',
    ],
    '/api/v1/projects/{projectId}/units/{unitSlug}': ['DELETE', 'GET', 'PUT'],
    '/api/v1/projects/{projectId}/verification-appeals': ['GET', 'POST'],
    '/api/v1/projects/{projectId}/verification-appeals/{appealId}': ['GET'],
    '/api/v1/regions/countries': ['GET'],
    '/api/v1/regions/popular': ['GET'],
    '/api/v1/regions/search': ['GET'],
    '/api/v1/regions/tree': ['GET'],
    '/api/v1/regions/{parentCode}/children': ['GET'],
    '/api/v1/regions/{regionCode}/places': ['GET'],
    '/api/v1/search': ['GET'],
    '/api/v1/search/discovery/categories': ['GET'],
    '/api/v1/search/discovery/popular': ['GET'],
    '/api/v1/search/place-region/demo/search-examples': ['GET'],
    '/api/v1/search/place-region/places/by-multiple-regions': ['GET'],
    '/api/v1/search/place-region/places/by-region-name': ['GET'],
    '/api/v1/search/place-region/places/by-region/{regionCode}': ['GET'],
    '/api/v1/search/place-region/places/{placeId}/region-hierarchy': ['GET'],
    '/api/v1/search/place-region/regions/{regionCode}/stats': ['GET'],
    '/api/v1/uploads': ['POST'],
    '/api/v1/uploads/my': ['GET'],
    '/api/v1/uploads/presigned-url': ['POST'],
    '/api/v1/uploads/{uploadId}': ['DELETE'],
    '/api/v1/uploads/{uploadId}/confirm': ['POST'],
    '/api/v1/users/me': ['GET', 'PATCH'],
    '/api/v1/users/me/access-level': ['GET'],
    '/api/v1/users/me/blocks': ['GET', 'POST'],
    '/api/v1/users/me/blocks/{targetUserId}': ['DELETE'],
    '/api/v1/users/me/favorites': ['DELETE', 'GET', 'POST'],
    '/api/v1/users/me/visits': ['GET'],
    '/api/v1/users/me/visits/summary': ['GET'],
    '/api/v1/users/me/visits/{visitId}': ['GET'],
    '/api/v1/users/search': ['GET'],
    '/api/v1/users/{userId}': ['GET'],
    '/api/v1/users/{userId}/blocked': ['GET'],
    '/api/v1/users/{userId}/follow': ['DELETE', 'GET', 'POST'],
    '/api/v1/users/{userId}/followers': ['GET'],
    '/api/v1/users/{userId}/following': ['GET'],
    '/api/v1/verification/challenge': ['GET'],
    '/api/v1/verification/config': ['GET'],
    '/api/v1/verification/keys': ['GET', 'POST'],
    '/api/v1/verification/keys/{keyId}': ['DELETE'],
  };

  /// EN: Returns whether a path template exists in the v3 spec.
  /// KO: 경로 템플릿이 v3 스펙에 존재하는지 반환합니다.
  static bool containsPath(String template) =>
      pathMethods.containsKey(template);
}
